export const SMARTZERO_TOOLS = [
  "reset_scene",
  "create_array",
  "create_variable",
  "update_variable",
  "create_pointer",
  "move_pointer",
  "highlight_element",
  "dim_elements",
  "compare",
  "set_bounds",
  "create_linked_list",
  "move_ll_pointer",
  "relink",
  "create_tree",
  "reveal_tree_node",
  "highlight_tree_node",
  "show_message",
  "show_complexity",
] as const;
